//ALLOCADA JOB (FB3),'ALLOCATE ADATA PDS',CLASS=A,MSGCLASS=H,
//         NOTIFY=&SYSUID,MSGLEVEL=(1,1)
//*
//* ============================================================
//* Allocate ADATA PDS for storing COBOL ADATA files
//* ============================================================
//*
//* This JCL allocates the partitioned dataset (PDS) that will
//* store ADATA files generated by the Enterprise COBOL compiler.
//*
//* Dataset: IN0050.CBSA.ADATA
//* Purpose: Store ADATA files for IBM Record Generator
//*
//ALLOC   EXEC PGM=IEFBR14
//ADATA   DD DSN=IN0050.CBSA.ADATA,
//           DISP=(NEW,CATLG,DELETE),
//           SPACE=(TRK,(50,25,50)),
//           DCB=(RECFM=VB,LRECL=32756,BLKSIZE=32760),
//           UNIT=SYSDA,
//           DSNTYPE=LIBRARY
//*
//* ============================================================
//* Dataset Attributes Explained:
//* ============================================================
//*
//* RECFM=VB     - Variable Blocked (required for ADATA files)
//* LRECL=32756  - Maximum logical record length for ADATA
//* BLKSIZE=32760 - Block size (LRECL + 4 bytes for control)
//* SPACE=(TRK,(50,25,50))
//*   - Primary: 50 tracks
//*   - Secondary: 25 tracks
//*   - Directory blocks: 50 (for member names)
//* DSNTYPE=LIBRARY - Indicates this is a PDS/PDSE
//*
//* ============================================================
//* After successful allocation, you can:
//* 1. Submit CUSTOMER_ADATA.jcl to generate ADATA files
//* 2. Submit GENERATE_ALL_ADATA.jcl to generate all ADATA files
//* ============================================================